DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MEMBER_ID	VARCHAR2(15),
	MEMBER_PW	VARCHAR2(13),
	MEMBER_NAME	VARCHAR2(15),
	MEMBER_AGE	NUMBER,
	MEMBER_GENDER	VARCHAR2(5),
	MEMBER_EMAIL	VARCHAR2(30),
	PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE MEMBERBOARD(
	BOARD_NUM	NUMBER,
	BOARD_ID	VARCHAR2(20), --È¸¿øID
	BOARD_SUBJECT	VARCHAR2(50),
	BOARD_CONTENT	VARCHAR2(2000),
	BOARD_FILE	VARCHAR2(50),
	BOARD_RE_REF	NUMBER,  --Ref
	BOARD_RE_LEV	NUMBER,  --depth
	BOARD_RE_SEQ	NUMBER,  --step
	BOARD_READCOUNT	NUMBER,
	BOARD_DATE	DATE,
	PRIMARY KEY(BOARD_NUM)
);

ALTER TABLE MEMBERBOARD
ADD CONSTRAINT fk_board_id FOREIGN KEY(board_id) 
REFERENCES member(member_id);



SELECT * FROM MEMBER;
SELECT * FROM MEMBERBOARD;