-- USER SQL
	CREATE USER SPRING IDENTIFIED BY 1004 
	DEFAULT TABLESPACE "USERS"
	TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
	ALTER USER SPRING QUOTA UNLIMITED ON USERS;

-- ROLES
	GRANT "CONNECT" TO SPRING ;
	GRANT "RESOURCE" TO SPRING ;